version: '3'

services:
  web:
    build: .
    command: python /code/hello_django/manage.py runserver 0.0.0.0:8001
    ports:
      - "8001:8001"
    volumes:
      - .:/code
    depends_on:
      - db
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      DJANGO_DB_NAME: 'postgres'
      DJANGO_SU_NAME: 'admin'
      DJANGO_SU_EMAIL: 'admin@email.com'
      DJANGO_SU_PASSWORD: 'admin@django'
      DJANGO_SECRET_KEY: 'gei!gp*q(!)3h-dn0m_$$gm85=a&w=_#qq()u%gy*yf7cmv5=w'

  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - backend

  db-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'postgres@mail.com'
      PGADMIN_DEFAULT_PASSWORD: 'postgres'
    depends_on:
      - db
    ports:
      - "8080:80"
    networks:
      - backend

networks:
  backend:
    driver: bridge
