version: '3.7'

services:
  app:
    build: ./web
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - backend

  db:
    build: ./db
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - backend

  dba:
    build: ./dba
    environment:
      PGADMIN_DEFAULT_EMAIL: 'pgadmin@mail.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin@pg123'
    depends_on:
      - db
    ports:
      - "8111:80"
    networks:
      - backend

# create a network
networks:
  backend:
    driver: bridge

volumes:
  pgdata:
