version: '3'

services:
  django:
    build: ./django
    ports:
      - 8000:8000
    networks:
      - nw_nginx

  nginx:
      build: ./nginx
      ports:
        - 8001:80
      networks:
        - nw_nginx
      depends_on:
        - django

# create a network
networks:
  nw_nginx:
    driver: bridge

# a volume for postgresql's persistant data
volumes:
  data:
