version: '3'

services:
  # django web+app server
  web:
    build: ./web
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - backend

  # database
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - backend

  # pgadmin4
  dba:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'pgadmin@mail.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin@pg123'
    depends_on:
      - db
    ports:
      - "8111:80"
    networks:
      - backend

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web

# create a network
networks:
  backend:
    driver: bridge

# a volume for postgresql's persistant data
volumes:
  postgres_data:
  static_volume:
  media_volume:
