version: '3'

services:
  djangoapp:
    build: ./django
    ports:
      - "8000:8000"
    networks:
      - backend

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    networks:
      - backend
    depends_on:
      - djangoapp

# create a network
networks:
  backend:
    driver: bridge
