version: '3'

services:
  # django container
  djangoapp:
    # location of the django dockerfile
    build: ./django
    volumes:
      # The below mapping ensures that changes at ./django/djangoapp of host get
      # reflected in realtime at /djangoapp of the container
      - ./django/djangoapp:/djangoapp
    ports:
      - "8000:8000"
    networks:
      - backend

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - djangoapp
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
