version: '3'

services:
  # django container
  djangoapp:
    # location of the django dockerfile
    build: ./django
    ports:
      - "8000:8000"
    networks:
      - backend

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - djangoapp
    networks:
      - backend

# create a network
networks:
  backend:
    driver: bridge
